workspace:
  base: /go
  path: src/github.com/uswitch/aws_usersync

pipeline:
  test:
    image: golang:1.9
    commands:
      - go test -v -cover $(go list ./... | grep -v /vendor)

  build:
    image: golang:1.9
    commands:
      - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/aws_usersync

  publish_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - bin/aws_usersync
    when:
      event: tag
